project_id = "jlhyoqfsyadxvuhfesmc"

[functions.register-sender]
verify_jwt = false

[functions.register-traveler]
verify_jwt = false

[functions.find-matching-trips]
verify_jwt = false

[functions.find-matching-parcels]
verify_jwt = false

[functions.accept-match]
verify_jwt = false

[functions.claim-parcel]
verify_jwt = false

[functions.upload-document]
verify_jwt = false
